export {HeaderHome} from './HeaderHome/HeaderHome'
export {FirstViewHome} from './FirstViewHome/FirstViewHome'
export {MiddleCards} from './MiddleCards/MiddleCards'
export {SecondViewHome} from './SecondViewHome/SecondViewHome'
export {ThirdViewHome} from './ThirdViewHome/ThirdViewHome'
export {default as HomeCard} from './HomeCard/HomeCard'