export { default as Button } from "./button/Button";
export { default as Navbar } from "./navbar/Navbar";
export { default as Title } from "./title/Title";
export { default as ContainerFlex } from "./container-flex/ContainerFlex";
export { default as Footer } from "./footer/Footer";
export { default as Logo } from "./logo/Logo";
export { default as Input } from "./input/Input"; 
export { default as Label } from "./label/Label";
export { default as TableComponent } from "./table-component/TableComponent";